
services:
  db-service:
    build: 
      context: .
      dockerfile: ./db-service/Dockerfile
    container_name: db-service
    restart: on-failure
    environment:
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DBNAME}
    depends_on:
      - postgres
    networks:
      - app-fintech-network

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"   # HTTP-интерфейс
      - "${CLICKHOUSE_TCP_PORT}:9000"   # TCP для клиентов
      - "${CLICKHOUSE_NATIVE_PROTOCOL}:9009"   # Native protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_config:/etc/clickhouse-server
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    networks:
      - app-fintech-network

  clickhouse_ui:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_ui
    ports:
      - "${CLICKHOUSE_UI_PORT}:8123"
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_HTTP_PORT=${CLICKHOUSE_HTTP_PORT}
      - CLICKHOUSE_LISTEN_HOST=0.0.0.0
    depends_on:
      - clickhouse
    networks:
      - app-fintech-network

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports: 
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-fintech-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8070:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-fintech-network

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    restart: on-failure
    volumes:
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana-dashboards:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
    depends_on:
      - postgres
    networks:
      - app-fintech-network


volumes:
  clickhouse_data:
  postgres-data:
  pgadmin_data:
  grafana-data:
  clickhouse_config:

networks:
  app-fintech-network:
    driver: bridge